Valor6800/FRC-6800-2023-code

src/main/cpp/controllers/ValorFalconController.cpp
src/main/cpp/controllers/ValorNeoController.cpp
src/main/cpp/subsystems/Drivetrain.cpp
src/main/cpp/subsystems/ValorSwerve.cpp
src/main/include/controllers/ValorController.h
src/main/include/controllers/ValorFalconController.h
src/main/include/controllers/ValorNeoController.h
src/main/include/subsystems/ValorSwerve.h

Include edge cases for if mag-encoder isn't found. Additionally if writing to the file is bad due to SD card issues
Lastly, set encoder based on rotations, not encoder count. This will help against switching between falcon and neo

Fix MagEncoder logic

---

build.gradle

Upgraded Wpilib version to v2023.2.1

Upgraded Wpilib version to v2023.2.1

---

src/main/cpp/auto/ValorAuto.cpp
src/main/cpp/subsystems/Drivetrain.cpp
src/main/include/Constants.h
src/main/include/ValorAuto.h
src/main/include/subsystems/Drivetrain.h

Making Everything Related to the number of swerve modules controlled by one constant (SWERVE_COUNT in drivetrain.h)

Drive train auto cleanup

---

src/main/cpp/subsystems/Drivetrain.cpp
src/main/include/subsystems/Drivetrain.h

Button X on operator controller. Holding it will override all movement from the robot.

added X-mode on operator controller

---

src/main/cpp/Robot.cpp
src/main/cpp/controllers/ValorNeoController.cpp
src/main/cpp/subsystems/Elevarm.cpp
src/main/include/controllers/ValorNeoController.h
src/main/include/subsystems/Elevarm.h

working automatic setpoints on robot with safeties for bounding box around chassis and edge cases for contacting.

Forward kin

---

src/main/cpp/Robot.cpp
src/main/cpp/controllers/ValorFalconController.cpp
src/main/cpp/controllers/ValorNeoController.cpp
src/main/cpp/subsystems/Drivetrain.cpp
src/main/cpp/subsystems/Elevarm.cpp
src/main/cpp/subsystems/Intake.cpp
src/main/include/controllers/ValorController.h
src/main/include/controllers/ValorFalconController.h
src/main/include/controllers/ValorNeoController.h
src/main/include/controllers/ValorNeutralMode.h
src/main/include/subsystems/Drivetrain.h

- replaces all instances of any rev or ctre specific idle/neutral modes
- removed some network table values replaced by logging

ValorNeutralMode

---

src/main/cpp/auto/ValorAuto.cpp

Use file names according to new file structur on roborio, automatically select red/blue points based on what's selected in the driver station.

Reformatted auto

---

src/main/cpp/Robot.cpp
src/main/cpp/subsystems/Drivetrain.cpp
src/main/include/subsystems/Drivetrain.h

Use driver station color to dictate what vision botpose to use.
Clean up the code

refactor: Drivetrain with simplified vision

---

.wpilib/wpilib_preferences.json
src/main/cpp/subsystems/ValorSwerve.cpp

module number is no longer flipped

---

src/main/cpp/subsystems/Elevarm.cpp
src/main/cpp/subsystems/Intake.cpp

removed extraneous comments and uncommented intake subsystem, removed extraneous manual control logic

cleaned up intake and elevarm subsystems

---

src/main/cpp/subsystems/Drivetrain.cpp
src/main/include/Constants.h

Added LimeLight Homing Function and optimized it to stop when facing straight at the retro-reflective tape.

added limelightHoming function

---

src/main/cpp/auto/ValorAuto.cpp
src/main/cpp/auto/ValorAutoAction.cpp
src/main/cpp/subsystems/Elevarm.cpp
src/main/include/auto/ValorAutoAction.h
src/main/include/subsystems/Elevarm.h

- Added `elevarm,<piece>,<direction>,<position>` command
- Fixed elevarm safety logic
- Fixed minAngle and check for floor

Elevarm auto test

---

src/main/cpp/auto/ValorAuto.cpp
src/main/cpp/auto/ValorAutoAction.cpp
src/main/cpp/subsystems/Elevarm.cpp
src/main/include/auto/ValorAuto.h
src/main/include/auto/ValorAutoAction.h
src/main/include/subsystems/Elevarm.h

- Added an option to make elevarm command parallel. Note that this doesn't actually add it to a parallelcommandgroup, just makes it exit the elevarm auto command isntantly
- Added code for parallel actions, but that and actions in general doesn't seem to work.

Working parallel elevarm command

---

scripts/auto/autos/balanceXMode.csv
src/main/cpp/auto/ValorAuto.cpp
src/main/cpp/auto/ValorAutoAction.cpp
src/main/cpp/subsystems/Drivetrain.cpp
src/main/include/auto/ValorAutoAction.h
src/main/include/subsystems/Drivetrain.h

Created the auto-balance functional command, tuned and ready for dev

Cjn auto level

---

scripts/auto/readme.md
src/main/cpp/subsystems/Elevarm.cpp

Working manual

---

src/main/cpp/subsystems/Drivetrain.cpp
src/main/include/subsystems/Drivetrain.h

Module diff updated to 2023 comp and prac bot size
moved module diff to drivetrain.cpp

Fix-Modulediff

---

src/main/cpp/subsystems/Elevarm.cpp
src/main/include/Constants.h
src/main/include/subsystems/Elevarm.h

working cancoder only for downward stow arm start withing robot boundaries

Cjn cancoder

---

src/main/cpp/controllers/ValorFalconController.cpp
src/main/cpp/sensors/ValorCurrentSensor.cpp
src/main/cpp/subsystems/Intake.cpp
src/main/include/Constants.h
src/main/include/subsystems/Intake.h

Tested new intake, changed stall current, cache size, and some logic to match the requirements of the new intake, tested on test bench with full functionality and good tuning

Fix(intake)!: new intake

---

src/main/cpp/auto/README.MD

Docs(auto): v1

---

scripts/auto/autos/barrier1_left.csv
scripts/auto/autos/barrier1_right.csv
scripts/auto/autos/wall1_left.csv
scripts/auto/autos/wall1_right.csv

1piece autos for waco start at scoring positions because arm now starts at snake
blocks #77

Fix(auto): 1 piece autos adjusted to start at scoring positions

---

src/main/cpp/subsystems/Elevarm.cpp

ground cone pickup angle tuned

fix(elevarm): ground cone pickup angle tuned

---

src/main/cpp/subsystems/Elevarm.cpp

driver control change

---

src/main/cpp/subsystems/Elevarm.cpp
src/main/cpp/subsystems/Intake.cpp
src/main/include/subsystems/Intake.h

Dynamic cache size and spiked setpoint based off piecstate

feature(intake): dynamic chace size and spike setpoint change based off piece

---

scripts/auto/autos/elevarmAutoTest.csv

fix: stow on end of elevarmautotest

fix: stow on end of elevarmautotest

---

src/main/cpp/subsystems/Intake.cpp
src/main/include/subsystems/Intake.h

operator right trigger overrides spike logic into order to reintake flopy cones

feat(intake): operator right trigger overrides spike logic

---

src/main/cpp/subsystems/Intake.cpp

Needs Testing, a relatively simple tree change

changed intake tree to match new changes made to controllers

---

src/main/cpp/subsystems/Elevarm.cpp

modifies controls layout for elevarm to include scope logic for all operator arm positions and added piece state change to operator Y button so that d pad only controls setpoints

new assesinputs for elevarm

---

src/main/cpp/auto/ValorAuto.cpp
src/main/cpp/subsystems/Elevarm.cpp
src/main/cpp/subsystems/Intake.cpp
src/main/include/auto/ValorAuto.h
src/main/include/subsystems/Direction.h
src/main/include/subsystems/Elevarm.h
src/main/include/subsystems/Intake.h
src/main/include/subsystems/Piece.h
src/main/include/subsystems/Position.h

Created a file for Piece, Position, and Direction each with an enum definition
Refactored Intake.h and intake.cpp as well as Elevarm.h and Elevarm.cpp to use new definitions

Piece direction state
